# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidBug',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=128)),
                ('package_version', models.CharField(max_length=128)),
                ('stacktrace', models.TextField(max_length=32768)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=32)),
                ('lat', models.DecimalField(decimal_places=10, max_digits=14)),
                ('lng', models.DecimalField(decimal_places=10, max_digits=14)),
                ('city', models.CharField(max_length=128)),
                ('region', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=128)),
                ('count', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Location')),
            ],
        ),
    ]
